"""empty message

Revision ID: 49950fc41364
Revises: 8387924e1a43
Create Date: 2017-11-03 09:47:01.493955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49950fc41364'
down_revision = '8387924e1a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('teg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['teg_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
